### ISSUE TITLE
CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by manumaiden** [DarrenOfficial/dpaste#267]
## Description

Received `Forbidden (403) CSRF verification failed. Request aborted.` error when click on the link

## Environment
```bash
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux dockerpi1.local 6.6.74+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.74-1+rpt1 (2025-01-27) aarch64 GNU/Linux
```

## Steps to reproduce
Using docker-compose.yml
```yaml
services:
  dpaste:
    container_name: dpaste
    image: darrenofficial/dpaste:latest
    restart: unless-stopped
    environment:
      DATABASE_URL: sqlite:////db/dpaste.sqlite
      PORT: 8000
      DEBUG: TRUE
    volumes:
      - ./data/db:/db
    ports:
      - "8055:8000"
```
Spinning with docker compose up -d command

## Expected result

New tab with the pasted result

## Actual result
This error:
```bash
Forbidden (403)

CSRF verification failed. Request aborted.

You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.

If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for “same-origin” requests.
```
Tested with chrome and firefox
